import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';
import globals from 'globals';

// Source of truth: .nitro/types/nitro-imports.d.ts (generated by `bunx nitropack prepare`)
const nitroGlobals = {
  createError: 'readonly',
  defineEventHandler: 'readonly',
  defineNitroConfig: 'readonly',
  readBody: 'readonly',
  getHeader: 'readonly',
  getRouterParam: 'readonly',
  getQuery: 'readonly',
  setResponseStatus: 'readonly',
  setResponseHeader: 'readonly',
  send: 'readonly',
  readValidatedBody: 'readonly',
  getValidatedQuery: 'readonly',
  defineRouteMeta: 'readonly',
  usePrisma: 'readonly',
  H3Event: 'readonly',
};

export default tseslint.config(
  {
    ignores: ['node_modules/', '.nitro/', '.output/', 'dist/', 'prisma/', 'generated/', 'realworld/'],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  prettier,
  {
    languageOptions: {
      globals: {
        ...globals.node,
        ...nitroGlobals,
      },
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
    },
  },
);
